### ISSUE TITLE
Feedback from today's lab session 

### ISSUE THREAD

**Issue by sweber15** [UBC-MDS/Victorious_Secret_DSCI_532#35]
Hi Victorious Secret, 

It was great seeing your project on San Francisco Crime. 

Some of our recommendations include:
-  The bar graph of crimes by neighbourhood should show that cumulative counts of the different crimes on the initial load. It wasn't easily understood that the initial bar counts were of all the crimes, unless you filter further and see it going down.  You can also arrange the order of the bars to show the neighbourhoods in descending order to show the best to worst neighbourhood. It would be easier to see changes.
- Add a title on the neighbourhood map
- Instructions and the write up were descriptive. It could be a little shorter to encourage readers to read it.

**Comment by PolinaRomanchenko** [comment]
Thank you for you feedback! We'll do our best in implementing it
